
services:
  portal_mysql:
    image: mysql:8.0
    container_name: portal_mysql
    restart: always
    command: --bind-address=0.0.0.0
    ports:
      - "3307:3306"
    env_file:
      - /envs/test-portal-mysql.env
    volumes:
      - portal_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - test-portal-network
      - reverse-proxy
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: test-portal-backend
    restart: unless-stopped
    ports:
      - "5003:5000"
    env_file:
      - /envs/test-portal-backend.env
    volumes:
      - ./backend/screenshots:/app/screenshots
      - ./backend/data:/app/data
      - /var/www/portal-assets:/var/www/portal-assets
    networks:
      - test-portal-network
      - reverse-proxy


  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_API_URL: ${VITE_API_URL}
        VITE_BACKEND_ORIGIN: ${VITE_BACKEND_ORIGIN}
    container_name: test-portal-frontend
    restart: unless-stopped
    ports:
      - "8083:80"
    env_file:
      - /envs/test-portal-frontend.env
    networks:
      - test-portal-network
      - reverse-proxy
    mem_limit: 512m
    cpus: "0.5"

networks:
  test-portal-network:
    driver: bridge
  reverse-proxy:
    external: true

volumes:
  portal_mysql_data:
