services:
  portal_mysql:
    image: mysql:8.0
    container_name: portal_mysql
    restart: always
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - portal_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - test-portal-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  backend:
    image: gokulv456/assessment-backend
    container_name: test-portal-backend
    restart: unless-stopped
    depends_on:
      portal_mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      # Point to Host DB (User's data is here)
      # Point to MySQL Container using service name
      DB_HOST: portal_mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      USE_JSON: ${USE_JSON}

      ASSETS_ROOT: /var/www/portal-assets

      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "100:7000"
    volumes:
      - ./backend/screenshots:/app/screenshots
      - ./frontend/dist:/app/public
      - ./backend/server.js:/app/server.js
      - ./backend/routes:/app/routes
      - ./backend/models:/app/models
      - ./backend/database:/app/database
      - /var/www/portal-assets:/var/www/portal-assets
    networks:
      - test-portal-network

networks:
  test-portal-network:
    driver: bridge

volumes:
  portal_mysql_data:
